### ISSUE TITLE
Helm template Standardization

### ISSUE THREAD

**Issue by jtcarnes** [openebs/mayastor-control-plane#253]
**Is your feature request related to a problem? Please describe.**
There are a few non-standard parameters in the current helm chart as well as a few parameters that would be desired by users
(being able to set a more specific image for instance).

**Describe the solution you'd like**
Modify some of the current helm chart parameters to align more with standard sets of parameters as well as modify
the templates slightly to allow users greater control in specifying things, while making their default values follow
what is currently hard coded.

**Additional context**
I know this is still in alpha and am willing to take it on myself if the current dev team is open to some changes.

**Comment by tiagolobocastro** [comment]
Hey @jtcarnes, we have now a chart on a single location: [here](https://github.com/openebs/mayastor-extensions/tree/develop/chart)
We're open to any suggestions or PR's :)
